# Generated by Django 4.2.11 on 2024-05-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frm', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mainx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('cantact', models.CharField(max_length=100)),
                ('portfilo', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('name', models.CharField(default='Syed Farman Ali', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Experience',
            fields=[
                ('eduction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.eduction')),
                ('p1', models.CharField(max_length=255)),
                ('p2', models.CharField(max_length=255)),
                ('p3', models.CharField(max_length=255)),
                ('p4', models.CharField(max_length=255)),
            ],
            bases=('main.eduction',),
        ),
    ]
